config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :artworks do
    resources :bookings, only: [:create, :new]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artwork.rb
class Artwork < ApplicationRecord
   has_many :bookings
   has_one_attached :photo
   geocoded_by :city
  after_validation :geocode, if: :will_save_change_to_city?
end

app/models/booking.rb
class Booking < ApplicationRecord
   belongs_to :artwork
   belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/artworks_controller.rb
class ArtworksController < ApplicationController
  before_action :artwork_find, only: [:show, :edit, :update]
  def index
    @artworks = Artwork.all
  end

  def show
     @artwork = Artwork.find(params[:id])
    # @artwork = Artwork.new
    @markers = [
      {
        lat: @artwork.latitude,
        lng: @artwork.longitude
      }
    ]
  end

  def new
    @artwork = Artwork.new
  end

  def create
    @artwork = Artwork.create(artwork_params)

    if @artwork.save
      redirect_to artwork_path(@artwork)
    else
      render "artworks/new"
    end
  end

  def edit
    # @artwork = Artwork.find(params[:id])
  end

  def update
    if @artwork.update(artwork_params)
      redirect_to artwork_path(@artwork)
    else
      render "artworks/edit"
    end
  end

  private

  def artwork_params
    params.require(:artwork).permit(:name, :artist, :description, :photo, :price, :city, :category, :size, :date)
  end

  def artwork_find
    @artwork = Artwork.find(params[:id])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = Booking.all
  end

   def show
     @booking = Booking.find(params[:id])
      # @artwork = Artwork.new
  end

  def new
    @booking = Booking.new
    @artwork = artwork
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.artwork = artwork
    if @booking.save
      redirect_to artwork_path(@booking.artwork)
    else
      render "artworks/new"
    end

  end

  private

  def booking_params
    params.require(:booking).permit(:start, :end)
  end

  def artwork
    artwork_id = params[:artwork_id]
    Artwork.find(artwork_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/artworks/_form.html.erb
<div class="container">
  <div class="form">
    <%= simple_form_for(artwork) do |f| %>
      <div id="name">
        <%= f.label :name %>
        <div id="input">
          <%= f.text_field :name %>
        </div>
      </div>
      <div id="artist">
        <%= f.label :artist %>
        <div id="input">
          <%= f.text_field :artist %>
        </div>
      </div>
      <div id="description">
        <%= f.label :description %>
        <div id="input">
          <%= f.text_field :description %>
        </div>
      </div>
      <div id="size">
        <%= f.label :size %>
        <div id="input">
          <%= f.text_field :size %>
        </div>
      </div>
      <div id="city">
        <%= f.label :city %>
        <div id="input">
          <%= f.text_field :city %>
        </div>
      </div>
      <div id="category">
        <%= f.label :category %>
        <div id="input">
          <%= f.text_field :category %>
        </div>
      </div>
      <div id="price">
        <%= f.label :price %>
        <div id="input">
          <%= f.text_field :price %>
        </div>
      </div>
        <%= f.input :photo, as: :file %>
      <%= f.submit %>
    <% end %>
  </div>
    <div class="buttons">
      <div id="backindex"><%= link_to "Back to artworks", artworks_path %></div>
    </div>
</div>

app/views/artworks/edit.html.erb
<div class="container">
<%= render "form", artwork: @artwork %>
</div>

app/views/artworks/index.html.erb
<div class="container">
  <div class="title">
    <h1>Artworks to rent</h1>
  </div>
  <div class="cards">
    <% @artworks.each do |artwork| %>
      <%= link_to artwork_path(artwork),class: "links" do %>
        <div class="card-artwork">
          <%= cl_image_tag artwork.photo.key, height: 400, width: 300, crop: :fill if artwork.photo.attached?%>
          <div class="card-artwork-infos">
            <div>
              <h2><%= artwork.artist %></h2>
              <p><%= artwork.name %></p>
            </div>
            <h2 class="card-artwork-pricing">
              <%= artwork.price %>
              <p>/day</p>
            </h2>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/artworks/new.html.erb
<%= render "form", artwork: @artwork %>

<%# <%= link_to "Show artworks", artworks_path %>

app/views/artworks/show.html.erb
<div class="container">
  <div class="elements">
    <div class="text_image">
      <div id="image">
        <%= cl_image_tag @artwork.photo.key, height: 400, width: 300, crop: :fill if @artwork.photo.attached?%>
      </div>
      <div id="text">
        <h2><%= @artwork.artist %></h2>
        <h4><%= @artwork.name %></h4>
        <h5><%= @artwork.description %></h5>
        <p><%= @artwork.date %></p>
        <p><%= @artwork.size %></p>
        <p><%= @artwork.city %></p>
        <p><%= @artwork.category %></p>
        <p><%= @artwork.price %>/day</p>
      </div>
    </div>
    <div id="map"
      style="width: 45%; height: 400px;"
      data-markers="<%= @markers.to_json %>"
      data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  </div>
  <h4 id='bookings'>Artwork bookings</h4>
  <ol>
    <% @artwork.bookings.each do |booking| %>
      <li> <%= booking.start %> <%= booking.end %></li>
    <% end %>
  </ol>
  <%# <%= link_to "Book", new_artwork_booking_path(@artwork), class: 'buttons' %>
  <%# <%= link_to "Back to artworks", artworks_path %>
  <%# <%= link_to "Edit", edit_artwork_path %>
  <div class="links-to">
    <div class="buttons">
        <div id="booknow"><%= link_to "Book", new_artwork_booking_path(@artwork) %></div>
        <div id="backindex"><%= link_to "Back to artworks", artworks_path %></div>
        <div id="editbtn"><%= link_to "Edit", edit_artwork_path %></div>
    </div>
  </div>
</div>

app/views/bookings/new.html.erb
<div class="page">  
  <div class="booking-page">
    <div class="left">
      <div class="booking-title">
          <h1>Booking form</h1>
      </div>
      <div id="image">
      <%= cl_image_tag @artwork.photo.key, height: 400, width: 300, crop: :fill if @artwork.photo.attached?%>
    </div>
    </div>
    <div class="right">
      <div class="booked-dates">
          <h4>Already booked dates</h4>
          <ol>
            <% @artwork.bookings.each do |booking| %>
              <li> <%= booking.start %> to <%= booking.end %></li>
            <% end %>
          </ol>
      </div>
      <div class="booking_form">
        <%= simple_form_for([@artwork,@booking]) do |f| %>
          <%= f.input :start, as: :date, html5: true %>
          <%= f.input :end, as: :date, html5: true %>
          
          <%= f.submit%>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RentArt</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<!-- <h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p> -->

<banner>
 <!--  <img src="<%= image_path('jpeg.jpg') %>" id="hero"> -->
 <div id="hero" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('<%= image_path('jpeg.jpg') %>')">
    <div class="title"><h2>Welcome to RentArt</h2>
    <div class="buttons">
      <div id="rentnow"><%= link_to "Rent now", artworks_path %></div>
      <div id="listnow"><%= link_to "List your Art", new_artwork_path %></div>
    </div>
  </div>
 </div>
</banner>

<div class="about_us_card">
  <div class="about_us">
    <div class="logo">
      <%= image_tag("logo.png", alt: "rss feed", height: 600, width: 600)%>
    </div>
    <p id="text">Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsum, minima quia odit recusandae ea. Omnis, deserunt, inventore debitis qui harum, mollitia voluptatum nulla magnam non, quidem molestias similique. Quia, id.
    Lorem ipsum dolor sit amet, consectetur adipisicing, elit. Nobis, aperiam explicabo provident reprehenderit dolores? Tenetur, beatae, architecto. Quidem voluptatum inventore quia odit itaque amet, magni assumenda deserunt! Veniam, repellendus nostrum.
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Et velit, similique cupiditate in cumque recusandae vero inventore corrupti laboriosam veritatis, tempora commodi at laudantium nemo eveniet consectetur, voluptas dolores suscipit! Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsum, minima quia odit recusandae ea. Omnis, deserunt, inventore debitis qui harum, mollitia voluptatum nulla magnam non, quidem molestias similique. Quia, id.
    Lorem ipsum dolor sit amet, consectetur adipisicing, elit. Nobis, aperiam explicabo provident reprehenderit dolores? Tenetur, beatae, architecto. Quidem voluptatum inventore quia odit itaque amet, magni assumenda deserunt! Veniam, repellendus nostrum.
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Et velit, similique cupiditate in cumque recusandae vero inventore corrupti laboriosam veritatis, tempora commodi at laudantium nemo eveniet consectetur, voluptas dolores suscipit!</p>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> at Le Wagon
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag('logo.png') %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <%# below is title in navbar div %>
  <div class='nav_buttons'>
    <ul id="nav_list">
      <li>
        <a href="/">Home</a>
      </li>
      <li>
        <a href="/artworks">All Artworks</a>
      </li>
    </ul>
  </div>
  <%# below is the redirection to all artwsorks in the navbar %>
<!--   <div>
    <h4 id="title-to-show">
     <a href="/artworks">All Artworks</a>
    </h4>
  </div> -->

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "/", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Show Artworks", "/artworks", class: "dropdown-item" %>
            <%= link_to "Add an artwork", "/artworks/new", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>